apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-controller
spec:
  project: vntechies
  destination:
    server: https://1470FBE09E07236EE4CF9E9295AE3126.gr7.ap-southeast-1.eks.amazonaws.com
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.11.3
    helm:
      version: v3
      values: |
        replicas: 2
        metrics:
          enabled: true
