apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: vntechies
  destination:
    server: https://1470FBE09E07236EE4CF9E9295AE3126.gr7.ap-southeast-1.eks.amazonaws.com
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.5.6
    helm:
      values: |
        txtOwnerId: hungran.cloud

        provider: cloudflare
        cloudflare:
          secretName: cloudflare-secret
          email: vmhung290791@gmail.com
          proxied: false

        domainFilters:
          - hungran.cloud

        sources:
          - service
          - ingress

        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
