apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
spec:
  project: cloud-day-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: http-echo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://ealenn.github.io/charts
    chart: echo-server
    targetRevision: 0.5.0
    helm: 
      values: |
        fullnameOverride: "http-echo-aws-cloud-demo-day"
        replicaCount: 2
        ingress:
          enabled: true
          ingressClassName: nginx
          tls:
            - secretName: http-echo-tls
              hosts:
                - http-echo.hungran.cloud
          hosts:
            host: http-echo.hungran.cloud
            path: "/"
