apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-day-demo
  namespace: argocd
spec:
  description: cloud-day-demo
  sourceRepos:
    - "*"

  destinations:
    - name: cloud-day-demo
      server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist: []