apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vntechies
  namespace: argocd
spec:
  description: vntechies
  sourceRepos:
    - "*"

  destinations:
    - name: vntechies
      server: https://1470FBE09E07236EE4CF9E9295AE3126.gr7.ap-southeast-1.eks.amazonaws.com
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist: []
