apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-day-demo-manifests
spec:
  project: cloud-day-demo
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/tnx-journey-to-cloud/demo-aws-clouday-vn.git
    targetRevision: HEAD
    path: application/ap-southeast-1/manifests
    directory:
      recurse: true