apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vntechies-manifests
spec:
  project: vntechies
  destination:
    server: https://1470FBE09E07236EE4CF9E9295AE3126.gr7.ap-southeast-1.eks.amazonaws.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/tnx-journey-to-cloud/demo-aws-clouday-vn.git
    targetRevision: HEAD
    path: application/ap-southeast-1/manifests
    directory:
      recurse: true
