# apiVersion: s3.aws.crossplane.io/v1beta1
# kind: Bucket
# metadata:
#   name: hung-test-bucket-20221021
#   namespace: default
# spec:
#   providerConfigRef:
#     name: aws-provider
#   forProvider:
#     locationConstraint: ap-southeast-1
#     acl: private
#     tagging:
#       tagSet:
#         - key: hungran
#           value: cloud
#         - key: email
#           value: me@hungran.cloud

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: hung-test-bucket-20230408
spec:
  forProvider:
    region: ap-southeast-1
    # locationConstraint: ap-southeast-1
    acl: private
    tagging:
      tagSet:
        - key: hungran
          value: cloud
        - key: email
          value: me@hungran.cloud
  providerConfigRef:
    name: aws-provider